owner: dsw-nrp
repo: status

sites:
  - name: DMP.eosc.cz
    url: https://dmp.eosc.cz
  - name: DMP.eosc.cz/wizard
    url: https://dmp.eosc.cz/wizard/

status-website:
  baseUrl: /status
  logoUrl: https://dsw-nrp.github.io/status/dsw-icon.svg
  name: "DMP in Czech NRP | Status"
  introTitle: "Status page for [**dmp.eosc.cz**](https://dmp.eosc.cz) services."
  introMessage: "This is status page monitors the availability of the DMP in National Repository Platform for Research Data (in Czech Republic) and related services. It also contains important information in case of outages, scheduled maintenance, and other incidents."
  themeUrl: https://dsw-nrp.github.io/status/custom-theme.css
  navbar:
    - title: Status
      href: /status
    - title: Homepage
      href: https://dmp.eosc.cz

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/15 * * * *"
